name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/Grpc.Net.Testing.Moq/
    - name: Build
      run: dotnet build --no-restore src/Grpc.Net.Testing.Moq/
    
  test:
  
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test --no-build --verbosity normal src/Grpc.Net.Testing.Moq/
    
  nuget:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v2
    - name: Nuget Publish
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Grpc.Net.Testing.Moq/Grpc.Net.Testing.Moq.csproj
        PACKAGE_NAME: Grpc.Net.Testing.Moq
        NUGET_KEY: ${{secrets.NUGET_API}}
        VERSION_STATIC: 1.0.0
